# Generated by Django 5.2.4 on 2025-07-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeProposal',
        ),
    ]
