# Generated by Django 5.2.4 on 2025-07-14 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_delete_exchangeproposal'),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeproposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('canceled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='exchangeproposal',
            constraint=models.UniqueConstraint(fields=('ad_sender', 'ad_receiver'), name='unique_proposal'),
        ),
    ]
